version: "3.7"

networks:
  proxy:
    external: true

services:
  proxy-inverso:
    image: nginx-proxy-inverso:4
    networks:
      - proxy
    volumes:
      - proxy-inverso-sites:/app/sites/enabled
      - proxy-inverso-html:/usr/share/nginx/html    
    ports:
      - 8888:80

# Definición de los volumenes
volumes:
  proxy-inverso-sites:
  proxy-inverso-html:
