version: "3.7"

networks:
  proxy:
    external: true

services:
  nginx:
    image: nginx-proxy-inverso:7
    restart: always
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxy-inverso-sites:/app/sites/enabled
      - proxy-inverso-html:/usr/share/nginx/html    

# Definición de los volumenes
volumes:
  proxy-inverso-sites:
  proxy-inverso-html:
